(* ::Package:: *)

BeginPackage["Taggar`MGroups`"]


MGroup::usage="MGroup represents a finite group in MGroups package."
FormMGroup::usage="FormMGroup[domain, operation] forms a group with the domain and (binary) operation."
MGroupDomain::usage="MGroupDomain[group] finds the domain of group."
MGroupIdentity::usage="MGroupIdentity[group] finds the identity of group."
MElementPower::usage="MElementPower[group, x, k] raises x to power k in group.
MElementPower[group, elements, k] raises elements to power k in group.
MElementPower[group, x, powers] raises element to powers in group."
MGroupOrder::usage="MGroupOrder[group] finds order of group."
MElementInverse::usage="MElementInverse[group, element] finds the inverse of element in group.
MElementInverse[group, elements] finds the inverses of elements in group."
MElementOrder::usage="MElementOrder[group, element] finds the order of element in group.
MElementOrder[group, elements] finds the orders of elements in group."
MCyclicQ::usage="MCyclicQ[group] checks whether group is cyclic or not.
MCyclicQ[group, subgroup] checks whether subgroup is cyclic or not."
MAbelianQ::usage="MAbelianQ[group] checks whether group is abelian or not.
MAbelianQ[group, subgroup] checks whether subgroup is abelian or not."
MCayleyTable::usage="MCayleyTable[group] prints the Cayley table of group."
MCayleyGraph::usage="MCayleyGraph[group, generators] draws the Cayley graph of group corresponding to generators."
MCayleyGraph3D::usage="MCayleyGraph3D[group, generators] draws the 3-D Cayley graph of group corresponding to generators."
MInversesTable::usage="MInversesTable[group] prints the table of inverses for group."
MSubgroupQ::usage="MSubgroupQ[group, subset] Check whether subset forms a subgroup of group or not."
MGenerateSubgroup::usage="MGenerateSubgroup[group, elements] generates the subgroup generated by elements.
MGenerateSubgroup[group, element] generates the subgroup generated by element."
MSubgroups::usage="MSubgroups[group] finds subgroups of group."
MSubgroupLattice::usage="MSubgroupLattice[group] draws the subgroup lattice of group."
MSubgroupLattice3D::usage="MSubgroupLattice3D[group] draws the 3-D subgroup lattice of group."
MCoset::usage="MCoset[group, subgroup, x, orientation] generates the left or right coset of group in subgroup represented by x."
MNormalSubgroupQ::usage="MNormalSubgroupQ[group, subgroup] checks whether subgroup is normal in group or not."
MNormalSubgroups::usage="MNormalSubgroups[group] finds all normal subgroups of group."
MFactorGroup::usage="MFactorGroup[group, subgroup] defines the factor group by subgroup."
MGroupCenter::usage="MGroupCenter[group] finds center of group."
MElementCentralizer::usage="MElementCentralizer[group, x] finds centralizer of x in group."
MAdditiveGroup::usage="MAdditiveGroup[n] defines the addivitive group of order n."
MMultiplicativeGroup::usage="MMultiplicativeGroup[n] defines the multiplicative group of order phi(n)."
MDihedralGroup::usage="MDihedralGroup[n] defines the dihedral group (symmetries of regular n-gon)."
MPermutationsGroup::usage="MPermutationsGroup[n] defines the group of permutation on n symbols.
MPermutationsGroup[permutations] defines the group of permutation on permutations."
MCycleForm::usage="MCycleForm[permutation] converts the string permutation into Mathematica's Cycles form."
MKlein4Group::usage="MKlein4Group represents the Klein 4-Group"
MQuaternionGroup::usage="MQuaternionGroup represents the Quaternion Group"
MEDP::usage="MEDP[groups] defines the external direct product of groups."
MHomomorphism::usage="MHomomorphism[\!\(\*SubscriptBox[\(group\), \(1\)]\), \!\(\*SubscriptBox[\(group\), \(2\)]\), phi] defines the homomorphism from \!\(\*SubscriptBox[\(group\), \(1\)]\) to \!\(\*SubscriptBox[\(group\), \(2\)]\) defined by phi."
MMorphismKernel::usage="MMorphismKernel[morphism] finds the kernel of morphism."
MIsomorphism::usage="MIsomorphism[\!\(\*SubscriptBox[\(group\), \(1\)]\), \!\(\*SubscriptBox[\(group\), \(2\)]\), phi] defines the isomorphism from \!\(\*SubscriptBox[\(group\), \(1\)]\) to \!\(\*SubscriptBox[\(group\), \(2\)]\) defined by phi."
MAutomorphism::usage="MAutomorphism[group, phi] defines the automorphism from group to itself defined by phi."
MInnerAutomorphism::usage="MInnerAutomorphism[group, x] defines the inner automorphism from group to itself induced by x."
MVisualiseMorphism::usage="MVisualiseMorphism[morphism] visualises morphism."
MAction::usage="MAction represents a group action."
FormMAction::usage="FormMAction[group, set, function] defines the group action of group on set defined by function."
MPermutationRepresentation::usage="MPermutationRepresentation[group, set, function] defines the permutation representation associated to the group action of group on set defined by function."
MKernelAction::usage="MKernelAction[action] finds kernel of action."
MElementStabilizer::usage="MElementStabilizer[action, a] finds stabilizer of a in action."
MElementOrbit::usage="MElementOrbit[action, a] finds orbit of a in action."

MCombinationsLimit::usage="Option for subgroups generation."
MHighlight::usage="Option for subgroup lattices."
MShowInfo::usage="Option for subgroup lattices."
MPresentation::usage="Option for presentation of subgroups."

MSymmetry::usage="MSymmetry[0, i] represents the ith rotation of a regular polygon.
MSymmetry[1, i] represents the ith reflection of a regular polygon."
MTuple::usage="MTuple[elements] denotes the tuple of elements in an external direct product."


Begin["`Private`"]


General::notin="The argument `1` is not a valid member of the group."
General::subset="The argument `1` is not a valid subset of the group."
General::subsetel="The argument is not a valid element or set of elements from the group."
General::subg="The argument `1` is not a valid subgroup of the group."
General::nsubg="The argument `1` is not a valid normal subgroup of the group."
General::OpPrev="The map does not preserve operation."
General::OneOne="The map is not one-one."
General::notins="The argument `1` does not belong to the set."


MGroup /: MakeBoxes[G_MGroup, form: TraditionalForm] := 
    Module[{domain = MGroupDomain[G],
    dr},
		dr = If[Length@domain > 5,
			(* a1, a2, ..., an *)
			"{"<>ToString@domain[[1]]<>", "<>
				ToString@domain[[2]]<>",..., "<>
				Last@dr<>"}",
			(* else the domain *)
			ToString@domain
		];
        ToBoxes[
            "MGroup["<>dr<>"]"
        ]
    ];

MGroup /: MakeBoxes[G_MGroup, form: StandardForm] := 
    Module[{above, below, icon},
        icon = Graphics[{
			EdgeForm[Black],
            FaceForm[LightBlue],
            Rectangle[],
            Text[Style["G", Black, 14], {0.5, 0.5}]
        }, ImageSize -> {30, 30}];
        above = {
            BoxForm`SummaryItem[{"Operation: ", "Binary", SpanFromLeft}],
            BoxForm`SummaryItem[{"Order: ", MGroupOrder@G}]
        };
        below = {
            BoxForm`SummaryItem[{"Identity: ", MGroupIdentity@G}]
        };
        BoxForm`ArrangeSummaryBox[
            "MGroup", G, icon, above, below, form,
            "Interpretable" -> True
        ]
    ];


mgClosure[g_, f_] := 
	AllTrue[Tuples[g, 2], MemberQ[g, f @@ #] &]
mgInverses[g_, f_] := Module[
	{id},
	id = Select[g, Function[e, AllTrue[g, f[e, #] === # === f[#, e] &]]];
	id = If[Length[id] == 1, First[id], Return[Missing["NoUniqueIdentity"]]];
	AllTrue[g, Function[x,
		AnyTrue[g, f[x, #] === id === f[#, x] &]
	]]
]
mgAssociativity[g_, f_] :=
	AllTrue[Tuples[g, 3],
		f[f[#[[1]], #[[2]]], #[[3]]] == f[#[[1]], f[#[[2]], #[[3]]]]&
	]


FormMGroup::inv = "The domain and function do not form a group."
FormMGroup[domain_List, binop_, check_: True] :=
    If[check === True,
        If[mgClosure[domain, binop] &&
           mgInverses[domain, binop] &&
           mgAssociativity[domain, binop],
            MGroup@
                AssociationThread[
                    domain,
                    Map[
                        AssociationThread[domain, #] &,
                        Transpose[Outer[binop, domain, domain]]
                    ]
                ],
            Message[FormMGroup::inv]
        ],
        MGroup@
            AssociationThread[
                domain,
                Map[
                    AssociationThread[domain, #] &,
                    Transpose[Outer[binop, domain, domain]]
                ]
            ]
    ]

MGroupData[MGroup[data_]] := data
MGroup /: g_MGroup[key1_][key2_] := MGroupData[g][key1][key2]
(* similarly *)
MGroup /: g_MGroup[key1_, key2_]:= MGroupData[g][key1][key2]
MGroupDomain[G_MGroup] := Keys@MGroupData@G
MGroupIdentity[G_MGroup] := With[
    {domain = MGroupDomain@G},
    SelectFirst[domain, And @@ Table[G[#][y] == y, {y, domain}] &]
]


ClearAll[MElementPower]

powerElement[G_, x_, n_Integer] := Module[
	{res, base, exp},
    If[n == 0, Return[MGroupIdentity[G]]];
    base = x; exp = n;
    If[n < 0, base = MElementInverse[G, x]; exp = -n];
    res = MGroupIdentity[G];
    While[exp > 0,
        If[OddQ[exp], res = G[res][base]];
        base = G[base][base];
        exp = Quotient[exp, 2]
    ];
    res
]

MElementPower[G_MGroup, elem_, p_] :=
	Module[{dom = MGroupDomain[G]},
		If[!MemberQ[dom, elem], Message[MElementPower::notin, elem]; Return[$Failed]];
		If[!IntegerQ[p], Message[MElementPower::pown, p]; Return[$Failed]];
		powerElement[G, elem, p]
	]

MElementPower[G_MGroup, elems_List, p_] :=
	Module[{dom = MGroupDomain[G], bad},
		bad = Select[elems, !MemberQ[dom, #] &];
		If[bad =!= {}, Message[MElementPower::notin, bad]; Return[$Failed]];
		If[!IntegerQ[p], Message[MElementPower::pown, p]; Return[$Failed]];
		powerElement[G, #, p] & /@ elems
	]

MElementPower[G_MGroup, elem_, ps_List] :=
	Module[{dom = MGroupDomain[G], bad},
		If[!MemberQ[dom, elem], Message[MElementPower::notin, elem]; Return[$Failed]];
		bad = Select[ps, Not@*IntegerQ];
		If[bad =!= {}, Message[MElementPower::pown, bad]; Return[$Failed]];
		powerElement[G, elem, #] & /@ ps
	]


MGroupOrder[G_MGroup] := Length@MGroupDomain@G

MElementOrder[G_MGroup, elem_] := 
	Module[{id = MGroupIdentity[G], div = Divisors[MGroupOrder[G]]},
		If[!MemberQ[MGroupDomain[G], elem], Return[$Failed]];
		FirstCase[div, d_ /; powerElement[G, elem, d] == id :> d, Null]
	]

MElementOrder[G_MGroup, elems_List] :=
	Module[{id = MGroupIdentity[G], div = Divisors[MGroupOrder[G]]},
		Map[Function[{elem}, FirstCase[div, d_ /; powerElement[G, elem, d] == id :> d, Null]], elems]
	]


MElementInverse[G_MGroup, elem_] :=
	Module[{dom = MGroupDomain[G], id = MGroupIdentity[G]},
		If[!MemberQ[dom, elem], Message[MElementInverse::notin, elem]; Return[$Failed]];
		SelectFirst[dom, G[elem, #] === id &, Null]
	]
MElementInverse[G_MGroup, elems_List] :=
	Module[{dom = MGroupDomain[G], bad, id = MGroupIdentity[G]},
		bad = Select[elems, !MemberQ[dom, #] &];
		If[bad =!= {}, Message[MElementInverse::notin, bad]; Return[$Failed]];
		Map[Function[{elem}, SelectFirst[dom, G[elem, #] === id &, Null]], elems]
	]


MCyclicQ[G_MGroup] := Module[
    {grouporder = MGroupOrder[G]},
    (* Groups of prime order are always cyclic, hence if so: *)
    If[PrimeQ[grouporder], True,
    (* else: *)
        FirstCase[
            MGroupDomain[G],
            x_ /; MElementOrder[G, x] == grouporder :> True,
            False
        ]
    ]
]
MCyclicQ[G_MGroup, H_List] := If[!SubsetQ[MGroupDomain[G], H],
	Message[MCyclicQ::subset, H],
	With[{o = Length@H},
	    (* Groups of prime order are always cyclic, hence if so: *)
	    If[PrimeQ@o, True,
	    (* else: *)
	        FirstCase[
	            H,
	            x_ /; MElementOrder[G, x] == o :> True,
	            False
	        ]
	    ]
	]
]


MAbelianQ[G_MGroup] := Module[
	{domain = MGroupDomain[G], n},
    n = Length[domain];
    If[n <= 4, Return[True]];
    Catch[
        (* iterate for i=1..n, j=i+1..n *)
        Do[
            If[G[domain[[i]], domain[[j]]] =!= G[domain[[j]], domain[[i]]], 
                Throw[False]
            ],
            {i, 1, n}, {j, i+1, n}
        ];
        Throw[True]
    ]
]
MAbelianQ[G_MGroup, H_List] := If[!SubsetQ[MGroupDomain[G], H],
	Message[MAbelianQ::subset, H],
	With[{n = Length[H]},
	    If[n <= 4, Return[True]];
	    Catch[
	        (* again with H *)
	        Do[
	            If[G[H[[i]]][H[[j]]] =!= G[H[[j]]][H[[i]]], 
	                Throw[False]
	            ],
	            {i, 1, n}, {j, i+1, n}
	        ];
	        Throw[True]
	    ]
	]
]


MCayleyTable[G_MGroup] := Module[{domain},
    domain = MGroupDomain[G];
    TableForm[
        Outer[G, domain, domain, 1],
        TableHeadings -> {domain, domain}, 
        TableDepth -> 2
    ]
]


MCayleyGraph[G_MGroup, gen_List] := Module[
	{ed, col, domain = MGroupDomain[G]},
	col = AssociationThread[gen ->
		(ColorData["Rainbow", #]& /@ Rescale@Range@Length@gen)];
	ed = Flatten[Table[
		Table[{y \[DirectedEdge] G[y][x], x}, {y, domain}],
		{x, gen}
	], 1];
	Graph[
		MGroupDomain[G],
		ed[[All,1]],
		EdgeStyle -> (#[[1]] -> col@#[[2]]& /@ ed),
		VertexLabels -> All,
		DirectedEdges -> False
	]
]

MCayleyGraph3D[G_MGroup, gen_List] := Module[
	{ed, col, domain = MGroupDomain[G]},
	col = AssociationThread[gen ->
		(ColorData["Rainbow", #]& /@ Rescale@Range@Length@gen)];
	ed = Flatten[Table[
		Table[{y \[DirectedEdge] G[y][x], x}, {y, domain}],
		{x, gen}
	], 1];
	Graph3D[
		MGroupDomain[G],
		ed[[All, 1]],
		EdgeStyle -> (#[[1]] -> col@#[[2]]& /@ ed),
		VertexLabels -> All,
		DirectedEdges -> False
	]
]


MInversesTable[G_MGroup] := Module[
	{domain},
	domain = MGroupDomain@G;
	TableForm[Table[{x, MElementInverse[G, x], MElementOrder[G, x]}, 
		{x, domain}],
	TableHeadings -> {None, {"x", 
		"\!\(\*SuperscriptBox[\(x\), \(-1\)]\)", 
		"|x|=|\!\(\*SuperscriptBox[\(x\), \(-1\)]\)|"}},
		TableDepth -> 2]
]


MGenerateSubgroup[G_MGroup, elements_List] := Module[
	{iden = MGroupIdentity[G],
	domain = MGroupDomain[G],
	H, Q, x, pr},
	(* Elements must be coming from the group, *)
	If[!SubsetQ[domain, elements],
		Message[MGenerateSubgroup::subsetel, elements]; $Failed,
		(* then: *)
		(* initiate the subgroup and a queue *)
		H = {iden};
		Q = {iden};
		While[
			(* the queue is non-empty *)
			Length[Q] > 0,
			x = First[Q];
			Q = Rest[Q];
			Do[
				(* keep appending s x to the queue if it isn't in the 
					subgroup already *)
				pr = G[x][s];
				If[!MemberQ[H, pr],
					AppendTo[H, pr];
					AppendTo[Q, pr];
				],
				{s, elements}
			];
		];
		Sort@H
	]
]
MGenerateSubgroup[G_MGroup, element_] :=
	MGenerateSubgroup[G, {element}]


MSubgroupQ[G_MGroup, H_List] := Module[
	{domain = MGroupDomain@G,
	identity = MGroupIdentity@G},
	If[!SubsetQ[domain, H],
		Message[MSubgroupQ::subset, H]; $Failed,
		Catch[
			(* subgroup ought to: have identity; *)
			If[!MemberQ[H, identity], Throw@False];
			(* and be closed under the operation of group itself. *)
			Do[If[!MemberQ[H, G[x][y]], Throw@False], {x, H}, {y, H}];
			(* Furthermore, by Lagrange theorem we can also discard H
				if its order does not divide the order of group itself,
				hence: *)
			If[!MemberQ[Divisors @ Length[domain],
				Length[H]], Throw@False];
			Throw@True
		]
	]
]


(* a helper function to calculate the subgroups *)
FindSubgroups[G_, r_:2] := Module[
    {domain = MGroupDomain[G], div, gen, subs},
    (* We check if the group is cyclic: *)
	gen = Null;
	Do[
		If[MGenerateSubgroup[G, {x}] == domain,
		gen = x],
		{x, domain}
	];
	(* if so: *)
	If[gen =!= Null,
		(* we apply the fundamental theorem of cyclic groups to
			exhibit subgroups using powers of the generator corresponding
			to each divisor d of group's order: *)
		div = Divisors@MGroupOrder@G;
		Table[
			With[{pow = MElementPower[G, gen, i]},
				{MGenerateSubgroup[G, {pow}], pow}],
			{i, div}],
		(* else-wise, we return unique subgroups generated by each subset A
			of G having cardinality less than or equal to r: *)
		subs = DeleteDuplicatesBy[
			Table[{MGenerateSubgroup[G, gen], gen}, {gen, Subsets[domain, {1, r}]}],
			#[[1]] &
		];
		If[MemberQ[subs[[All, 1]], Sort@domain],
			Return@subs,
			Return[subs~Append~{domain, Null}]
		]
	]
]
Options[MSubgroups] = {MCombinationsLimit -> 2, MPresentation -> "Table"};
MSubgroups[G_MGroup, OptionsPattern[]] := With[
	{subs = FindSubgroups[G, OptionValue[MCombinationsLimit]]},
	Switch[
		OptionValue[MPresentation],
		"Table",
		TableForm[subs,
		TableHeadings -> {None, {"Subgroup", "Generated by"}},
			TableDepth -> 2],
		"Raw",
		subs,
		"Subgroups",
		subs[[All,1]]
	]
]		


showinfoAll[sub_] := Grid[{
	{sub[[1]]},
	{"Generated by "<>ToString@sub[[2]]},
	{"Order = "<>ToString @ Length @ sub[[1]]}
}, Frame -> All]
showinfoNotAll[sub_] := ToString[sub[[2]]]

Options[MSubgroupLattice] = {MHighlight -> "All", MShowInfo -> "All", MCombinationsLimit -> 2};
MSubgroupLattice[G_MGroup, OptionsPattern[]] := Module[
	{subgroups, rel, colourRule},
	
	colourRule = If[
		OptionValue[MHighlight] === "All",
			(# -> RGBColor["#4983FE"]) &,
			(# -> If[
				OptionValue[MHighlight][G, #[[1]]],
					RGBColor["#4983FE"], LightGray
			]) &
	];
  
	subgroups = FindSubgroups[G, OptionValue[MCombinationsLimit]];
	rel = Select[Tuples[subgroups, 2], SubsetQ[#[[1]][[1]], #[[2]][[1]]] &];
	
	TransitiveReductionGraph[
		Rule @@@ rel,
		GraphLayout->"LayeredDigraphEmbedding",
		VertexStyle -> colourRule/@subgroups,
		VertexSize -> Medium,
		VertexLabels -> If[OptionValue[MShowInfo] == "All",
				(#->Placed[showinfoAll[#], Tooltip]&/@subgroups),
				(#->showinfoNotAll[#]&/@subgroups)],
		EdgeStyle -> Gray
	]
];

Options[MSubgroupLattice3D] = {MHighlight -> "All", MShowInfo -> "All", MCombinationsLimit -> 2};
MSubgroupLattice3D[G_MGroup, OptionsPattern[]] := Module[
	{subgroups, rel, colourRule},
	
	colourRule = If[
		OptionValue[MHighlight] === "All",
			(# -> RGBColor["#4983FE"]) &,
			(# -> If[
				OptionValue[MHighlight][G, #[[1]]],
					RGBColor["#4983FE"], LightGray
			]) &
	];
  
	subgroups = FindSubgroups[G, OptionValue[MCombinationsLimit]];
	rel = Select[Tuples[subgroups, 2], SubsetQ[#[[1]][[1]], #[[2]][[1]]] &];
	
	Graph3D[
		EdgeList @ TransitiveReductionGraph[Rule @@@ rel],
		GraphLayout->"LayeredDigraphEmbedding",
		VertexStyle -> colourRule/@subgroups,
		VertexLabels -> If[OptionValue[MShowInfo] == "All",
				(#->Placed[showinfoAll[#], Tooltip]&/@subgroups),
				(#->showinfoNotAll[#]&/@subgroups)],
		EdgeStyle -> LightGray
	]
];


MCoset::orien="The third argument expects 'l' or 'r', received `1`."

MCoset[G_MGroup, H_, element_, orientation_ : "l"] := Module[
    {domain = MGroupDomain@G},
    If[!MSubgroupQ[G, H],
		Message[MCoset::subg, H]; Return[$Failed]];
	If[!MemberQ[domain, element],
		Message[MCoset::notin, element]; Return[$Failed]];
	If[!MemberQ[{"l", "r"}, orientation],
		Message[MCoset::orien, orientation]; Return[$Failed]];
    If[orientation == "l",
            G[#][element] & /@ H,
            G[element][#] & /@ H
        ]
]


MNormalSubgroupQ::sub="The argument `1` is not a valid subgroup of the group."
Options[MNormalSubgroupQ] = {CheckSub -> True};
MNormalSubgroupQ[G_MGroup, H_] := Module[
	{domain = MGroupDomain@G},
	Catch[If[OptionValue[CheckSub],
		If[!MSubgroupQ[G, H],
			Message[MNormalSubgroupQ::sub, H]; Return[$Failed]]];
	Do[If[
		Sort[MCoset[G, H, x, "l"]]
		=!= Sort[MCoset[G, H, x, "r"]],
		Throw[False]
	],
	{x, domain}];
	Throw@True]
]


Options[MNormalSubgroups] = {MCombinationsLimit -> 2, MPresentation -> "Table"};
MNormalSubgroups[G_MGroup, OptionsPattern[]] := Module[
	{ns},
	ns = Select[
		FindSubgroups[G, OptionValue[MCombinationsLimit]],
		MNormalSubgroupQ[G, #[[1]]] &
	];
	Switch[
		OptionValue[MPresentation],
		"Table",
		TableForm[
		ns,
		TableHeadings -> {None, {"Subgroup", "Generated by"}},
			TableDepth -> 2],
		"Raw",
		ns,
		"Subgroups",
		ns[[All,1]]
	]
]


MFactorGroup[G_MGroup, H_List] := Module[
	{domain = MGroupDomain@G, csc, ur, map},
	If[!MNormalSubgroupQ[G, H],
		Message[MFactorGroup::nsubg, H]; Return[$Failed]];
	csc = <|Table[el -> Table[G[x][el], {x, H}], {el, domain}]|>;
	ur = DeleteDuplicatesBy[
		domain,
		Sort@csc[#] &
	];
	Do[
		map[x] = SelectFirst[ur, Sort@csc[x] == Sort@csc[#] &],
		{x, domain}
	];
	FormMGroup[ur, map[G[#1][#2]] &, False]
]


MGroupCenter[G_MGroup] := Module[
	{domain = MGroupDomain@G},
	Select[domain,
		And@@Table[G[#][y] == G[y][#], {y, domain}] &]
]
MElementCentralizer[G_MGroup, elem_] := Module[
	{domain = MGroupDomain@G},
	Select[domain, G[#][elem] == G[elem][#] & ]
]


MAdditiveGroup[n_Integer] := FormMGroup[Range[0, n-1], Mod[#1+#2, n] &, False]


MMultiplicativeGroup[n_Integer] := FormMGroup[
	Select[Range[n-1], GCD[#, n] == 1 & ],
	Mod[#1 #2, n] &,
	False
]


Format[MSymmetry[0, 0]] := "e";
Format[MSymmetry[0, i_]] := Superscript["r", i];
Format[MSymmetry[1, 0]] := "s";
Format[MSymmetry[1, i_]] := Row[{Superscript["r",i], "s"}];

dihedralOperation[n_][MSymmetry[0, n1_], MSymmetry[0, n2_]] := 
    MSymmetry[0, Mod[n1 + n2, n]];
dihedralOperation[n_][MSymmetry[0, n1_], MSymmetry[1, n2_]] := 
    MSymmetry[1, Mod[n1 + n2, n]];
dihedralOperation[n_][MSymmetry[1, n1_], MSymmetry[0, n2_]] := 
    MSymmetry[1, Mod[n1 - n2, n]];
dihedralOperation[n_][MSymmetry[1, n1_], MSymmetry[1, n2_]] := 
    MSymmetry[0, Mod[n1 - n2, n]];
    
MDihedralGroup[n_Integer] := Module[
    {members},
    
    members = Join[
        Table[MSymmetry[0, i], {i, 0, n - 1}],
        Table[MSymmetry[1, i], {i, 0, n - 1}]
    ];
    FormMGroup[members, dihedralOperation[n], False]
]


Unprotect[Cycles];
permCycleFormat[list_List] := Row[{"(", Row[list, ""], ")"}]
Format[cyc_Cycles] := Row[permCycleFormat /@ cyc[[1]], ""]
Format[Cycles[{}]] := "(1)"
MPermutationsGroup[n_Integer] := Module[{domain},
    domain = PermutationCycles /@ Permutations[Range[n]];
    FormMGroup[domain, PermutationProduct, False]
]
MPermutationsGroup[gens_List] := Module[{domain},
    domain = GroupElements@PermutationGroup[gens];
    FormMGroup[domain, PermutationProduct, False]
]
Protect[Cycles];


MKlein4Group:=MGroup@<|
	"e" -> <|"e" -> "e", "a" -> "a", "b" -> "b", "c" -> "c"|>,
	"a" -> <|"e" -> "a", "a" -> "e", "b" -> "c", "c" -> "b"|>,
	"b" -> <|"e" -> "b", "a" -> "c", "b" -> "e", "c" -> "a"|>,
	"c" -> <|"e" -> "c", "a" -> "b", "b" -> "a", "c" -> "e"|>
|>


MQuaternionGroup:=MGroup@<|
	"1" -> <|"1" -> "1", "-1" -> "-1", "i" -> "i", "-i" -> "-i", "j" -> "j", "-j" -> "-j", "k" -> "k", "-k" -> "-k"|>,
	"-1" -> <|"1" -> "-1", "-1" -> "1", "i" -> "-i", "-i" -> "i", "j" -> "-j", "-j" -> "j", "k" -> "-k", "-k" -> "k"|>,
	"i" -> <|"1" -> "i", "-1" -> "-i", "i" -> "-1", "-i" -> "1", "j" -> "k", "-j" -> "-k", "k" -> "-j", "-k" -> "j"|>,
	"-i" -> <|"1" -> "-i", "-1" -> "i", "i" -> "1", "-i" -> "-1", "j" -> "-k", "-j" -> "k", "k" -> "j", "-k" -> "-j"|>,
	"j" -> <|"1" -> "j", "-1" -> "-j", "i" -> "-k", "-i" -> "k", "j" -> "-1", "-j" -> "1", "k" -> "i", "-k" -> "-i"|>,
	"-j" -> <|"1" -> "-j", "-1" -> "j", "i" -> "k", "-i" -> "-k", "j" -> "1", "-j" -> "-1", "k" -> "-i", "-k" -> "i"|>,
	"k" -> <|"1" -> "k", "-1" -> "-k", "i" -> "j", "-i" -> "-j", "j" -> "-i", "-j" -> "i", "k" -> "-1", "-k" -> "1"|>,
	"-k" -> <|"1" -> "-k", "-1" -> "k", "i" -> "-j", "-i" -> "j", "j" -> "i", "-j" -> "-i", "k" -> "1", "-k" -> "-1"|>
|>


(* We wrap the elements of EDP --- that are in list form --- using
	an MTuple head, to avoid conflicts with list manipulations and
	pattern matchings elsewhere. Note for example, that
	MElementInverse[G, {0, 1}] otherwise could be taken to mean inverses
	of 0 and 1, AND inverse of tuple {0, 1} as well. *)
MTuple /: MTuple[elems___][[i_]] := {elems}[[i]]
Format[MTuple[elems___]] :=
  Row[{"(", Row[{elems}, ","],")"}]

MEDP[groups___MGroup] := With[
	(* number of groups in question: *)
	{n = Length @ {groups}},
	(* Forming the group: *)
	FormMGroup[
		(* with elements being tuples of groups *)
		MTuple @@@ Tuples[MGroupDomain /@ {groups}],
		(* and the operation being component wise *)
		MTuple@@Table[{groups}[[i]][#1[[i]]][#2[[i]]], {i, n}] &,
		False
	]
]
CirclePlus /: CirclePlus[groups___MGroup] := MEDP[groups]


FormMMorphism[from_, to_, by_] := 
	MMorphism[<|
		"Map" -> <|Map[# -> by@# &, MGroupDomain@from]|>,
		"Domain" -> from,
		"CoDomain" -> to
	|>]
MMorphismData[MMorphism[data_], key_] := data[key]
MMorphism /: M_MMorphism[key_] := MMorphismData[M, "Map"][key]


MMorphism /: MakeBoxes[M_MMorphism, form: TraditionalForm] := 
    Module[{},
        SubsuperscriptBox[
            StyleBox["MMorphism", FontSlant -> "Italic"],
            ToBoxes[Length@MGroupDomain@MMorphismData[M, "Domain"], form],
            ToBoxes[Length@MGroupDomain@MMorphismData[M, "CoDomain"], form]
        ]
    ];

MMorphism /: MakeBoxes[M_MMorphism, form: StandardForm] := 
    Module[{above, below, icon},
        icon = Graphics[{
			EdgeForm[Black],
            FaceForm[LightOrange],
            Rectangle[],
            Text[Style["M", Black, 14], {0.5, 0.5}]
        }, ImageSize -> {30, 30}];
        above = {
            BoxForm`SummaryItem[{"Type: ", "MMorphism", SpanFromLeft}],
            BoxForm`SummaryItem[{"n-1: ", ToString@Length@MGroupDomain@MMorphismData[M, "Domain"]<>
            " to "<>ToString@Length@MGroupDomain@MMorphismData[M, "CoDomain"]}]
        };
        below = {
			BoxForm`SummaryItem[{"Kernel: ", MMorphismKernel@M}]
        };
        BoxForm`ArrangeSummaryBox[
            "MMorphism", M, icon, above, below, form,
            "Interpretable" -> True
        ]
    ]


MHomomorphism[G1_MGroup, G2_MGroup, def_] := Module[
	{domain},
	domain = MGroupDomain[G1];
	If[Or@@Flatten[Table[
		def[G1[x][y]] != G2[def@x][def@y],
		{x, domain}, {y, domain}]],
		Message[MHomomorphism::OpPrev]; Return[$Failed]];
	FormMMorphism[G1, G2, def]
	
]


MMorphismKernel[M_MMorphism] := Module[
	{identity},
	identity = MGroupIdentity[MMorphismData[M, "CoDomain"]];
	Select[MGroupDomain@MMorphismData[M, "Domain"], M@# == identity & ]
]


MIsomorphism[G1_MGroup, G2_MGroup, def_] := Module[
	{domain, mapped},
	domain = MGroupDomain[G1];
	If[Or@@Flatten[Table[
		def[G1[x][y]] != G2[def@x][def@y],
		{x, domain}, {y, domain}]],
		Message[MIsomorphism::OpPrev]; Return[$Failed]];
	If[Length[domain] != DeleteDuplicates[def/@domain],
		Message[MIsomorphism::OneOne]; Return[$Failed]];
	FormMMorphism[G1, G2, def]
]


MAutomorphism[G_MGroup, def_] := MIsomorphism[G, G, def]


MInnerAutomorphism[G_MGroup, x_] := 
	If[!MemberQ[MGroupDomain[G], x],
		Message[MInnerAutomorphism::notin, x]; $Failed,
	MAutomorphism[G, G[G[x][#]][MElementInverse[G, x]] & ]
]


MVisualiseMorphism[M_MMorphism] := 
	Module[
		{data, s, shape, uv, vc},
		data = MMorphismData[M, "Map"];
		s = SortBy[data, data[#] & ];
		shape[list_] := Partition[list, Ceiling[Sqrt[Length[list]]]];
		uv = Values@DeleteDuplicates[s];
		vc=AssociationThread[uv -> 
			(ColorData["Pastel"][#]&/@Rescale[Range[Length[uv]]])
		];
		ArrayPlot[
			shape[Keys@s],
			ColorRules -> (# -> vc@data@# & /@ Keys@s),
			Frame -> All,
			Mesh -> All,
			PlotLegends -> Automatic
		]
	]


FormMAction::closed="The action is not closed."
FormMAction::one="Property 1 fails."
FormMAction::two="Property 2 fails."
FormMAction[G_, A_, f_] := Module[
	{e = MGroupIdentity@G,
	d = MGroupDomain@G,
	mapping},
	mapping = Association[Rule@@@({#, f@@#} &/@Tuples[{d, A}])];
	If[!SubsetQ[A, Values@mapping],
		Message[FormMAction::closed]; Return[$Failed]];
	If[Or@@@
		(f[#[[1]], f[#[[2]], #[[3]]]] != f[G[#[[1]]][#[[2]]], #[[3]]] & /@
			Tuples[{d, d, A}]),
		Message[FormMAction::one]; Return[$Failed]];
	If[Or@@@
		(f[e, #] != # &/@d),
		Message[FormMAction::two]; Return[$Failed]];
	MAction[<|
		"G" -> G,
		"A" -> A,
		"Mapping" -> mapping
	|>]
]


MActionData[MAction[data_], key_] := data[key]
MAction /: A_MAction[{g_, a_}] := MActionData[A, "Mapping"]{g, a}


MAction /: MakeBoxes[A_MAction, form_] := 
    Module[{above, below, icon},
        icon = Graphics[{
			EdgeForm[Black],
            FaceForm[LightOrange],
            Rectangle[],
            Text[Style["A", Black, 14], {0.5, 0.5}]
        }, ImageSize -> {30, 30}];
        above = {
            BoxForm`SummaryItem[{"Type: ", "MAction", SpanFromLeft}],
            BoxForm`SummaryItem[{"A: ", MActionData[A, "A"]}]
        };
        below = {
			BoxForm`SummaryItem[{"Kernel: ", MActionKernel[A]}]
        };
        BoxForm`ArrangeSummaryBox[
            "MAction", A, icon, above, below, form,
            "Interpretable" -> True
        ]
    ]


MPermutationRepresentation[A_MAction] := 
	MHomomorphism[
		MActionData[A, "G"],
		MPermutationsGroup@Length@MActionData[A, "A"],
		Function[{a}, A[{#, a}]] /@ MActionData[A, "A"] &
	]


MActionKernel[A_MAction] := Module[
	{G, set},
	G = MGroupDomain[MActionData[A, "G"]];
	set = MActionData[A, "A"];
	Select[
		G,
		And@@Table[A[{#, a}] == a, {a, set}] &
	]
]
MElementStabilizer[A_MAction, a_] := With[
	{G = MGroupDomain[MActionData[A, "G"]]},
	If[!MemberQ[MActionData[A, "A"], a],
		Message[MElementStabilizer::notins, a]; $Failed,
		Select[
			G,
			A[{#, a}] == a &
		]
	]
]
MElementOrbit[A_MAction, a_] := With[{set = MActionData[A, "A"]},
	If[!MemberQ[set, a],
		Message[MElementOrbit::notins, a]; $Failed,
		A[{#, a}] & /@ set // DeleteDuplicates
	]
]


End[]
EndPackage[]
